import streamlit as st
from utils.emotion_detector import predict_emotion
from utils.bert_model import predict_emotion_bert
from utils.gemini_helper import generate_learning_content

# =====================================================
# PAGE CONFIGURATION
# =====================================================

st.set_page_config(
    page_title="Emotion Detection Learning Support Engine",
    page_icon="🧠",
    layout="wide",
    initial_sidebar_state="expanded"
)

# =====================================================
# LOAD CSS
# =====================================================

def load_css():
    try:
        with open("style.css", "r", encoding="utf-8") as css:
            st.markdown(
                f"<style>{css.read()}</style>",
                unsafe_allow_html=True
            )
    except:
        pass

load_css()

# =====================================================
# SIDEBAR
# =====================================================

st.sidebar.title("🧠 Emotion AI Dashboard")

page = st.sidebar.radio(
    "Navigation",
    [
        "🏠 Home",
        "😊 Emotion Detection",
        "🤖 AI Learning Support",
        "ℹ️ About"
    ]
)

st.sidebar.markdown("---")

st.sidebar.metric("BiLSTM Accuracy", "89%")
st.sidebar.metric("BERT Accuracy", "92%")

st.sidebar.markdown("---")

st.sidebar.success("✅ Models Loaded")

# =====================================================
# HOME PAGE
# =====================================================

if page == "🏠 Home":

    st.title("🧠 Emotion Detection Learning Support Engine")

    st.markdown("""
Welcome to the **Emotion Detection Learning Support Engine**.

This application combines **BiLSTM**, **BERT**, and **Gemini AI**
to detect emotions from text and provide personalized learning support.
""")

    st.markdown("---")

    col1, col2, col3 = st.columns(3)

    with col1:
        st.info("""
### 😊 Emotion Detection

✔ Detect emotions

✔ Student sentiment

✔ Text Analysis
""")

    with col2:
        st.success("""
### 🤖 BERT

✔ Transformer

✔ Context Aware

✔ High Accuracy
""")

    with col3:
        st.warning("""
### 📚 Gemini AI

✔ Learning Support

✔ Easy Explanations

✔ Smart Assistance
""")

    st.markdown("---")

    a, b, c = st.columns(3)

    with a:
        st.metric("Models", "2")

    with b:
        st.metric("Accuracy", "92%")

    with c:
        st.metric("Status", "Ready")
# =====================================================
# EMOTION DETECTION PAGE
# =====================================================

elif page == "😊 Emotion Detection":

    st.title("😊 Emotion Detection Dashboard")

    st.write(
        "Compare predictions generated by the **BiLSTM** and **BERT** models."
    )

    user_text = st.text_area(
        "Enter your text",
        height=180,
        placeholder="Example: I am feeling very happy today."
    )

    detect = st.button(
        "🚀 Detect Emotion",
        use_container_width=True
    )

    if detect:

        if user_text.strip() == "":
            st.warning("Please enter some text.")

        else:

            with st.spinner("Analyzing emotion..."):

                # -----------------------------
                # BiLSTM Prediction
                # -----------------------------
                try:
                    bilstm_result = predict_emotion(user_text)
                except Exception as e:
                    bilstm_result = f"Error: {e}"

                # -----------------------------
                # BERT Prediction
                # -----------------------------
                try:
                    bert_result, confidence = predict_emotion_bert(user_text)
                except Exception:
                    bert_result = "Model Not Loaded"
                    confidence = 0.0

            st.success("✅ Emotion Analysis Completed")

            col1, col2 = st.columns(2)

            with col1:

                st.subheader("🧠 BiLSTM Model")

                st.success(bilstm_result)

                st.metric(
                    "Accuracy",
                    "89%"
                )

            with col2:

                st.subheader("🤖 BERT Model")

                st.success(bert_result)

                st.metric(
                    "Confidence",
                    f"{confidence*100:.2f}%"
                )

            st.markdown("---")

            st.subheader("📊 Confidence Score")

            st.progress(float(confidence))

            confidence_percent = confidence * 100

            st.metric(
                label="BERT Confidence",
                value=f"{confidence_percent:.2f}%"
            )

            if confidence_percent >= 90:
                st.success("🟢 Very High Confidence Prediction")

            elif confidence_percent >= 75:
                st.info("🔵 High Confidence Prediction")

            elif confidence_percent >= 50:
                st.warning("🟡 Medium Confidence Prediction")

            else:
                st.error("🔴 Low Confidence Prediction")

            
# =====================================================
# AI LEARNING SUPPORT
# =====================================================

elif page == "🤖 AI Learning Support":

    st.title("🤖 Gemini AI Learning Support")

    st.markdown("""
Generate easy-to-understand explanations for any topic using **Google Gemini AI**.
""")

    topic = st.text_input(
        "📚 Enter a topic",
        placeholder="Example: Artificial Intelligence"
    )

    difficulty = st.selectbox(
        "🎓 Select Difficulty Level",
        [
            "Beginner",
            "Intermediate",
            "Advanced"
        ]
    )

    if st.button(
        "✨ Generate Learning Content",
        use_container_width=True
    ):

        if topic.strip() == "":

            st.warning("Please enter a topic.")

        else:

            with st.spinner("Generating AI Content..."):

                prompt = f"""
Explain the topic '{topic}' for a {difficulty} level student.

Include:

1. Introduction
2. Explanation
3. Real-life Example
4. Advantages
5. Disadvantages
6. Key Points
7. Summary
"""

                answer = generate_learning_content(prompt)

            st.success("✅ Content Generated Successfully")

            st.markdown("---")

            st.subheader("📖 AI Explanation")

            st.write(answer)

            st.markdown("---")

            col1, col2, col3 = st.columns(3)

            with col1:
                st.metric(
                    "Topic",
                    topic
                )

            with col2:
                st.metric(
                    "Difficulty",
                    difficulty
                )

            with col3:
                st.metric(
                    "AI",
                    "Gemini"
                )

            st.info(
                "💡 Tip: Try topics like Python, Machine Learning, DBMS, Operating Systems, Computer Networks, Artificial Intelligence, Data Structures, or Cloud Computing."
            )
# =====================================================
# ABOUT PAGE
# =====================================================

elif page == "ℹ️ About":

    st.title("ℹ️ About This Project")

    st.markdown("""
# 🧠 Emotion Detection Learning Support Engine

This project is an AI-powered learning support system that detects emotions from student text and generates personalized learning content.

---

## 🚀 Technologies Used

- 🐍 Python
- 🎈 Streamlit
- 🧠 BiLSTM (TensorFlow/Keras)
- 🤖 BERT (Hugging Face Transformers)
- 📚 Google Gemini AI
- 🔥 Scikit-learn
- 📊 Pandas & NumPy

---

## 🎯 Features

✅ Emotion Detection using BiLSTM

✅ Emotion Detection using BERT

✅ Confidence Score

✅ AI Learning Support

✅ Professional Dashboard

✅ Interactive User Interface

---

## 📊 Model Comparison

| Model | Accuracy |
|--------|----------|
| BiLSTM | 89% |
| BERT | 92% |

---

## 👩‍💻 Developed By

**Sakeena Syed**

Bachelor of Technology

Artificial Intelligence & Data Science

---

Thank you for using the Emotion Detection Learning Support Engine!
""")

    st.markdown("---")

    col1, col2, col3 = st.columns(3)

    with col1:
        st.metric("BiLSTM", "89%")

    with col2:
        st.metric("BERT", "92%")

    with col3:
        st.metric("Status", "Ready")

# =====================================================
# FOOTER
# =====================================================

st.markdown("---")

st.markdown(
    """
<div style='text-align:center; padding:15px; color:gray;'>

<h4>🧠 Emotion Detection Learning Support Engine</h4>

<p>Powered by <b>BiLSTM</b> | <b>BERT</b> | <b>Google Gemini AI</b> | <b>Streamlit</b></p>


</div>
""",
unsafe_allow_html=True
)